---
title: "BME548L"
author: "Zhixiang Yao"
date: "2023-03-26"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(gridExtra)
library(factoextra)
library(tidyverse)
library(ggplot2)
library(corrplot)
library(utils)
library(MASS)
library(ROCR)
library(caret)
library(gmodels)
library(class) # Knn algorithm
library(patchwork)
library(psych)

```

```{r}
DL <- read.table('/Users/zhixiangyao/Desktop/Spring\ 2023/Machine\ Learning/Project/DL_info.csv', header=T, sep=',')
```

```{r}
# Find out images annotated with multiple lesions
duplicate_rows <- subset(DL,duplicated(File_name))
list_duplicate <- as.list(duplicate_rows$File_name)
cleaned1 <- DL[ ! DL$File_name %in% list_duplicate, ]
# Remove noisy images
cleaned2 <- subset(cleaned1,Possibly_noisy == 0 )
# Drop unnecessary columns from the dataset
cols_to_drop <-  c('Patient_index', 'Study_index', 'Series_ID',
                   'Possibly_noisy', 'Slice_range', 'Patient_gender',
                   'Patient_age', 'Image_size', 'Spacing_mm_px', 
                   'DICOM_windows')

cleaned3 <- cleaned2[ , !names(cleaned2) %in% cols_to_drop]
# Split train_valid_test
DL_train <- subset(cleaned3, Train_Val_Test == 1)
Dl_val <- subset(cleaned3, Train_Val_Test == 2)
Dl_test <- subset(cleaned3, Train_Val_Test == 3)

write.csv(DL_train, "/Users/zhixiangyao/Desktop/Spring\ 2023/Machine\ Learning/Project/DL_train.csv", row.names=FALSE)
write.csv(Dl_val, "/Users/zhixiangyao/Desktop/Spring\ 2023/Machine\ Learning/Project/Dl_val.csv", row.names=FALSE)
write.csv(Dl_test, "/Users/zhixiangyao/Desktop/Spring\ 2023/Machine\ Learning/Project/Dl_test.csv", row.names=FALSE)
```


